version: 2.1
executors:
  builder:
    docker:
      - image: docker:git
    environment:
      GLIBC_VERSION: 2.32
    working_directory: ~/docker-glibc-builder
  artefact-uploader:
    docker:
      - image: golang:alpine
    working_directory: ~/docker-glibc-builder
jobs:
  build:
     executor: builder
     steps:
      - run:
          name: Activate QEMU
          command:
            docker run -it --rm --privileged multiarch/qemu-user-static --reset --credential yes --persistent yes
      - run:
          name: Build flow
          no_output_timeout: 30m
          command: |
            docker build -t mohneeshjha/glibc-builder:$CIRCLE_SHA1 -f Dockerfile_aarch64 .
            docker run --rm --env GLIBC_VERSION --env STDOUT=1 sgerrand/glibc-builder:$CIRCLE_SHA1 > artefacts/glibc-bin-$GLIBC_VERSION-0-$(uname -m).tar.gz
      - persist_to_workspace:
          root: .
          paths: artefacts
      - store_artifacts:
          path: artefacts
      - persist_to_workspace:
          root: .
          paths: artefacts
      - store_artifacts:
          path: artefacts


  upload-master:
    executor: artefact-uploader
    steps:
      - run:
          command: apk add --no-cache git openssh-client
          name: Install dependencies of go get
      - attach_workspace:
          at: .
      - run:
          command: go get github.com/tcnksm/ghr
          name: Install ghr executable
      - deploy:
          name: Upload to GitHub release
          command: ghr -r $CIRCLE_PROJECT_REPONAME -u $CIRCLE_PROJECT_USERNAME --prerelease --delete unreleased artefacts
workflows:
  build-compile-upload:
    jobs:
      - build
      - upload-master:
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
          requires:
            - build
  
