version: 2
jobs:
build:
  docker:
    - image: jdrouet/docker-with-buildx:stable
  steps:
    - checkout
    - setup_remote_docker:
        version: 18.09.3
    - run: docker login -u "mohneeshjha" -p "Rishiarchanapragya@123"
    - run: |
        docker buildx build --push \
          --platform linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/i386,linux/amd64
          --tag mohneeshkjha/glibc-builder:$CIRCLE_SHA1.
